#!/bin/sh

L=~/p/lua/root/local/lua-5.1.4/src
V=/usr/local/include/vortex

x="$A $V $B $L"

# --file-tags=yes   Same as --extra=+f  ?
# --extra=+g   Unsupported?

ctags --if0=yes --file-tags=yes --recurse --extra=+fq --fields=+i --ruby-kinds=+cfFm --c-kinds=+p $x .

# on work branch
