#!/bin/sh

L=~/p/lua/root/local/lua-5.1.4/src

x="$C $A $G $L"

# --file-tags=yes   Same as --extra=+f  ?
# --extra=+g   Unsupported?

ctags --if0=yes --file-tags=yes --recurse --extra=+fq --fields=+i --ruby-kinds=+cfFm $x .

