#!/usr/bin/env lua

require"quote"
require"sockext"

-- Setup

q = quote.quote

USAGE = "usage: "..arg[0].." <port> [host]"

SZ = 4000
BUF = string.rep("x", SZ)
TIME = 5 -- seconds

if arg[1] == "-v" then
  verbose = true
  table.remove(arg, 1)
end

port = assert(tonumber(arg[1]), "no port\n"..USAGE)
host = arg[2] or "localhost"

local xfersz = 0

function receive(client)
  if verbose then print(".. receive", "here") end

  data, emsg = client:receive"*l"

  if verbose then print(q(data), q(emsg)) end

  assert(data, emsg)

  xfersz = xfersz + assert(tonumber(data))

  if verbose then
    print(".. xfersz = "..xfersz)
  end

  t1 = os.time()

  if t1 - t0 > TIME then
    t = t1 - t0
    print("tcp", "b", xfersz, "t", t, "rate", xfersz/1000/t, "kb/s")
    os.exit(0)
  end
end

function send(client)
  if verbose then print(".. send") end

  local sz = assert(client:send(BUF))

  if verbose then
    print(".. sendsz = "..sz)
  end
end

if verbose then
  print("connecting...")
end

client = assert(socket.connect(host, port))

if verbose then
  print("starting...", receive, send)
end

t0 = os.time()

loop = sockext.loop

loop._debug = true

loop.receive(client, receive)
loop.send(client, send)
loop.start()

