#!/usr/bin/env lua

require"quote"
require"swirlsock"


-- Arguments

q = quote.quote

CHAT = "http://example.com/beep/chat"

USAGE = "usage: "..arg[0].." <port>"

port = assert(tonumber(arg[1]), "no port\n"..USAGE)


-- Chat server:

users = {}

function join(core, chno, name)
  if not name then
    return swirl.ecodes.invalidparam, "chat content is not the name"
  elseif core.user then
    return swirl.ecodes.invalidparam, "chatting already"
  else
    print("ADD USER", q(name))
    core.user = { name = name, chno = chno }
    users[name] = core
  end
end

function leave(core, chno)
  print("DROP USER", q(core.user.name))
  core.user = nil
end

function speak(core, payload, more)
  core.user.msg = (core.user.msg or "")..payload

  if more then
    print("MSG FROM", core.user.name, "...")
    return
  end

  print("MSG FROM", core.user.name)
  print(core.user.msg)

  -- send msg to all users other than ours
  for _,other in pairs(users) do
    if other ~= core  and other.user then
      print("@", q(other.user.name))
      other:send_msg(other.user.chno, core.user.name.." says "..q(core.user.msg))
    end
  end

  core.user.msg = nil
end


-- Bind swirl to chat server

chat = {
  profiles = {CHAT}
}

function chat.on_start(ch0)
  print(".. on_start:", ch0:channelno(), q(ch0:profiles()), q(ch0:servername()))
  local p
  for i, profile in pairs(ch0:profiles()) do
    if profile.uri == CHAT then
      p = profile
      break
    end
  end
  if not p then
    ch0:reject(swirl.ecodes.unavailable)
    return
  end

  local ecode, emsg = join(ch0:core(), ch0:channelno(), p.content)

  if ecode then
    ch0:reject(ecode, emsg)
  else
    ch0:accept(p.uri)
  end
end

function chat.on_close(ch0)
  local ecode, emsg, elang = ch0:error()
  print(".. on_close:", ch0:core(), ch0:channelno(), ecode, q(emsg), elang)

  leave(ch0:core())

  ch0:accept()
end

function chat.on_msg(frame)
  local core, more, payload = frame:core(), frame:more(), frame:payload()
  print(".. on_msg:", core, frame:channelno(), frame:messageno(), more, #payload)

  speak(core, payload, more)

  if not frame:more() then
    core:send_rpy(frame:channelno(), frame:messageno(), "")
  end

  frame:destroy()
end

function chat.on_disconnected(core, emsg)
  print("DIED", core.user and core.user.name, emsg)
end

swirl.listen(chat, port)

swirl.loop.start()

